### PR TITLE
Feature/documentation

### PR DESCRIPTION
**Pull request by AyushyaChitransh**
Modified README.md: Containing all the text for documentation.

Modified docker-compose.yml: `wordpress-sites` to use `wordpress.env`, mysql-database in develop branch already uses `wordpress.env`

Modified wordpress.env: Removed non-essential variables.

Added prereqs-ubuntu.sh: File which installs prerequisites.

Added documentation-images/all-services.png
Added documentation-images/mysql-for-tomcat.png
Added documentation-images/mysql-for-wordpress.png
Added documentation-images/neo4j-db.png
Added documentation-images/solr.png
Added documentation-images/tomcat.png
Added documentation-images/wordpress-sites.png

### CODE REVIEW

**Comment by AyushyaChitransh** [comment]
I have mentioned about most of the logs but one log from [build_solr_index.sh](https://github.com/reactome/container/blob/feature/build_solr_index/java-application-builder/build_solr_index.sh#L11) is getting stored inside the `java-application-builder` directory.

We can use `dirname` to refer to parent directory and get all logs in one place. Or if the logs are meant to be stored there then we could add that information in README.

**Comment by AyushyaChitransh** [comment]
I tried few things but didn't reach any fruitful result. We can modify few files inside `/opt/solr/server` as described [here](https://stackoverflow.com/a/39310582/6207775). 

I earlier tried with mounting `/opt/solr/server` but that removed other mounts. I will get back with this later today.

**Comment by SolomonShorser-OICR** [comment]
That was the link I found too. I'm going to have a look at some of our production servers to see how it's done there. It _shouldn't_ be that hard...

Worst case scenario (If we can't get something working soon): I'll open an new issue and assign it to myself to work on later. I don't want this to delay your GSoC final submission.

**Comment by AyushyaChitransh** [comment]
Okay, till then I'll try and see if I can get it working. And by default, solr accepts connections from localhost only, and by default, no login screen is shown and localhost logs in directly.

**Comment by SolomonShorser-OICR** [comment]
Oh, Ok. I didn't realize that it would only accept local connections by default. Still, I'd like to get passwords working. I will also try something here.

**Comment by AyushyaChitransh** [comment]
I got it working, I'll push the changes related to solr in a new branch soon.

**Comment by SolomonShorser-OICR** [comment]
Ok, great to hear!

**Pull request merged**
