### PR TITLE
Feature/download script

### PR DESCRIPTION
**Pull request by AyushyaChitransh**
The download script is ready to be used. Current behavior of download section in `deploy.sh`:

1. If system is online then verify database are updated or not.
2. If updates are required, then remove old file before downloading new one.

This can be further improved by 

1.  Adding resume download feature.
2. Making update check optional by implementing flags while running script.

### CODE REVIEW

**Comment by SolomonShorser-OICR** [comment]
If this pull request is ready for merging, please let me know and assign it to me.

**Comment by AyushyaChitransh** [comment]
This pull request is now ready to be merged

**Comment by SolomonShorser-OICR** [comment]
Testing now, will merge to develop if everything looks ok...

**Comment by AyushyaChitransh** [comment]
I've merged them in my local, and will push the changes.

**Pull request merged**
