### PR TITLE
Multiple fixes

### LINKED ISSUE #55: Joomla branch: Submodule URL won't work if cloned from https
Currently the Joomla branch pulls the website from `git@github.com:reactome/Website.git` which is a SSH url. Since this repository is public, most people are going to pull it using https which means that the submodule won't pull correctly and has to be pulled manually. One alternative would be to simply use relative path (`../Website.git`), but this will break the submodule for forks, so changing the URL to https would be the best choice.

### PR DESCRIPTION
**Pull request by zingmars**
Closes #55. List of fixes in this PR:

* Added ols-client library that's required by the Curator-Tool. I sourced the file from [here](https://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/uk/ac/ebi/ols/ols-client/1.18/ols-client-1.18.jar).
* Fix for #55 - Changed git submodule path to a HTTPS one since it prevents cloning the submodules on a machine on which a SSH key is not set up
* Fixed a typo that prevented solr from finding EHLDs
* Switched to a branch of search-indexer that doesn't throw a NPE when getting the icons (when it will be merged into master, someone should switch it back)
* Removed a duplicate Config.pm file for Joomla
* Added information to README about which uid/gid should be set for solr and neo4j log directories

This is what it took to get it to build and run. Haven't tested if everything works 100% correctly yet, but it looks good enough for now.

### CODE REVIEW

**Comment by SolomonShorser-OICR** [comment]
Hi @zingmars,
Thanks for this PR! Overall, these fixes look pretty good. Some of these changes may clash with some of my local (unpushed) work, so I may need to cherry-pick commits rather than merging the whole PR; I'm not sure yet which will work better, and it might be a while before I can complete this...

Also, I'm curious: Are you planning to build and run Reactome in containers locally?

**Comment by zingmars** [comment]
> Some of these changes may clash with some of my local (unpushed) work, so I may need to cherry-pick commits rather than merging the whole PR

Alright, my objective was to simply get the build to work properly.

> Also, I'm curious: Are you planning to build and run Reactome in containers locally?

That's the idea, although I'll probably be cutting parts I'm not using. The reason for this is because Reactome only stores analysis results for 7 days (_maybe_ more, depending on use), whereas I would prefer to keep them for as long as I need them and then delete them when I don't.

I haven't looked into it yet, but I don't suppose you know how reactome handles the deletion of old Analysis results? I would very much like to turn that off.

**Comment by SolomonShorser-OICR** [comment]
I'm not sure about the code that deletes the analysis after 7 days of not being used. I can ask around to see if anyone knows how to change that.

**Comment by SolomonShorser-OICR** [comment]
...And I really do appreciate any commits that can get this project to a smoother build! ;) 

There's a newer branch for the search-indexer that you might find interesting if you want to test it locally, as it should speed up the indexing time significantly (though it will put a heavier load on your system).

**Comment by zingmars** [comment]
Thank you for the heads up. I'll try that branch when I have the time for it.

> I can ask around to see if anyone knows how to change that.

Thank you, that would be great. The only thing I found that handle deletions was https://github.com/reactome-pwp/utils which apparently can be configured in [AnalysisService_mvc-dispatcher-servlet.xml](https://github.com/reactome/container/blob/feature/Joomla/tomcat/java-build-mounts/AnalysisService_mvc-dispatcher-servlet.xml), although I haven't tested it yet. Would be great to have some actual confirmation by someone who knows the system.

**Comment by SolomonShorser-OICR** [comment]
I heard back from one of the other developers who explained to me that the ttl value doesn't take effect until the size threshold is reached. 

The code that I was referred to is here, in LruFolderContentChecker:
https://github.com/reactome-pwp/utils/blob/25e9b6a631ad2067ac887945521ba92d5a8c55d3/src/main/java/org/reactome/server/utils/lru/LruFolderContentChecker.java

So if you run the analysis service locally, you could adjust both the size _and_ ttl to keep the analysis files around for longer.

**Comment by zingmars** [comment]
Okay, good to know. Thanks!

**Comment by SolomonShorser-OICR** [comment]
@zingmars In further discussions with other team members, someone pointed out that there is the "report" endpoint of the AnalysisService that lets you export your analysis to a PDF: 

https://reactome.org/AnalysisService/#/report/generatePdfReportUsingGET

Personally, I'm not very familiar with all of the endpoints of this web service, but another developer suggested that you might find this useful.

Another option might be trying to build a stand-alone AnalysisService: https://github.com/reactome/container/tree/0d91e3695b73e8cb96f6a3575f229d00c0007e10/stand-alone-analysis-service

This is still very much a work-in-progress, but I started it so that users who _only_ wanted to do analysis could run this as a lightweight alternative to trying to run the full Reactome ecosystem. This project might be a little rougher around the edges than the main "full" Reactome-in-docker, and has had less testing. But, it is also less complex, so it might work OK for your needs.

**Comment by SolomonShorser-OICR** [comment]
The docker-compose file is not being used actively, at the moment. Development has focused on the stand-alone images. I'm closing the PR as I think some of these changes/fixes might have already been integrated manually, and some might not be relevant anymore. You can now pull stand-alone Reactome docker images from here: https://hub.docker.com/u/reactome

**Pull request closed without merging**
